on:
  push:
    branches:
      - master
      - doc*
strategy:
  matrix:
    coq_version:
      - '8.13.2'
    ocaml_version: ['4.12.0']
  fail-fast: false  # don't stop jobs if one fails

jobs:
  build:
    runs-on: ubuntu-latest  # container actions require GNU/Linux
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-domains.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

